# =============================================================================
# significance.R -- Permutation Significance Testing for Pathway Importance
#
# Tests whether each pathway's importance score is statistically significant
# by comparing against a null distribution. The null is constructed by
# randomly redistributing learned weight magnitudes across pathways while
# preserving pathway sizes — no Julia calls during permutation.
# =============================================================================

#' Permutation Significance Testing for Pathway Importance
#'
#' Assesses statistical significance of per-pathway importance scores by
#' comparing observed scores against a null distribution generated by
#' randomly redistributing weight magnitudes across pathways.
#'
#' @details
#' ## Null Model
#'
#' The observed importance of pathway \eqn{j} is
#' \eqn{I_j = \sum_i |W_{ij} \cdot M_{ij}|}, where \eqn{W} is the trained
#' weight matrix and \eqn{M} is the binary mask.
#'
#' Under the null hypothesis, gene-pathway assignments carry no biological
#' signal. We operationalize this by pooling all absolute nonzero weights
#' from the masked weight matrix, shuffling them, and redistributing into
#' pathway-sized bins matching the original pathway gene counts. This
#' preserves:
#' \itemize{
#'   \item The total weight budget (same pool of learned magnitudes)
#'   \item Pathway size structure (larger pathways get more weights)
#'   \item The marginal distribution of weight magnitudes
#' }
#'
#' The test asks: "Is this pathway's total weight magnitude unusual given
#' its size and the overall distribution of learned weights?"
#'
#' ## P-value Computation
#'
#' Empirical one-tailed p-values with pseudocount:
#' \eqn{p = (r + 1) / (B + 1)} where \eqn{r} is the number of null
#' statistics \eqn{\geq} the observed statistic and \eqn{B} is the number
#' of permutations. Multiple testing correction uses Benjamini-Hochberg.
#'
#' @param model A trained \code{VNNModel} object.
#' @param n_perm Integer. Number of permutations. Default 1000.
#' @param layer Integer. Which layer to test (1-indexed). Default 1L.
#' @param seed Integer. Random seed for reproducibility. Default 42L.
#' @param weight_matrix Optional pre-extracted weight matrix
#'   (\code{[genes x pathways]}). If \code{NULL}, the matrix is extracted
#'   from the Julia backend via \code{get_masked_weights}. Providing this
#'   allows fully Julia-free operation for pre-computed results.
#' @param verbose Logical. Print progress? Default TRUE.
#'
#' @return A \code{data.frame} with columns:
#'   \describe{
#'     \item{\code{pathway}}{Pathway name.}
#'     \item{\code{observed}}{Observed importance score.}
#'     \item{\code{pathway_size}}{Number of genes in the pathway.}
#'     \item{\code{null_mean}}{Mean of the null distribution.}
#'     \item{\code{null_sd}}{Standard deviation of the null distribution.}
#'     \item{\code{z_score}}{Standardized score: (observed - null_mean) / null_sd.}
#'     \item{\code{p_value}}{Empirical one-tailed p-value.}
#'     \item{\code{p_adj}}{BH-adjusted p-value.}
#'   }
#'   Rows are sorted by \code{p_value} ascending.
#'
#' @importFrom stats p.adjust sd
#'
#' @export
#' @examples
#' \donttest{
#' # After training:
#' # perm <- permutePathwayImportance(model, n_perm = 1000)
#' # head(perm)
#' # plotPermutationResults(perm)
#' }
permutePathwayImportance <- function(model,
                                     n_perm = 1000L,
                                     layer = 1L,
                                     seed = 42L,
                                     weight_matrix = NULL,
                                     verbose = TRUE) {

    ## ---- input validation ---------------------------------------------------
    stopifnot(is(model, "VNNModel"))
    n_perm <- as.integer(n_perm)
    layer <- as.integer(layer)

    if (n_perm < 10L) {
        stop("n_perm must be >= 10 for meaningful p-values.")
    }

    arch <- architecture(model)
    masks <- layerMasks(arch)

    if (layer > length(masks)) {
        stop(sprintf("Requested layer %d but model only has %d layer(s).",
                     layer, length(masks)))
    }

    ## ---- obtain weight matrix -----------------------------------------------
    if (is.null(weight_matrix)) {
        model_ref <- model@julia_model_ref
        if (is.null(model_ref)) {
            stop("Model has no Julia reference and no weight_matrix provided. ",
                 "Either train the model first or pass a pre-extracted ",
                 "weight_matrix (e.g., from a saved analysis).",
                 call. = FALSE)
        }
        if (!requireNamespace("JuliaConnectoR", quietly = TRUE)) {
            stop("JuliaConnectoR required to extract weights. ",
                 "Pass weight_matrix to run without Julia.",
                 call. = FALSE)
        }
        W <- as.matrix(
            JuliaConnectoR::juliaCall("_vnn_get_masked_weights",
                                      as.integer(layer), model_ref)
        )
    } else {
        W <- as.matrix(weight_matrix)
    }

    ## ---- get mask for pathway sizes and names -------------------------------
    mask <- as.matrix(masks[[layer]])

    if (nrow(W) != nrow(mask) || ncol(W) != ncol(mask)) {
        stop(sprintf(
            paste0("weight_matrix dimensions [%d x %d] do not match ",
                   "mask dimensions [%d x %d]."),
            nrow(W), ncol(W), nrow(mask), ncol(mask)
        ))
    }

    # Apply mask dimnames to W for labeling
    if (!is.null(colnames(mask))) colnames(W) <- colnames(mask)
    if (!is.null(rownames(mask))) rownames(W) <- rownames(mask)

    ## ---- observed importance -------------------------------------------------
    observed <- colSums(abs(W))
    n_pathways <- length(observed)

    ## ---- pathway sizes (genes per pathway from mask) -------------------------
    pw_sizes <- as.integer(colSums(mask != 0))

    ## ---- pool all weights at mask positions ----------------------------------
    ## Use mask positions (not W != 0) to include trained-to-zero weights
    abs_vals <- abs(W[mask != 0])
    n_total <- length(abs_vals)

    if (n_total == 0) {
        stop("No nonzero mask entries found. Cannot compute permutation null.")
    }

    ## Sanity check: sum of pathway sizes should equal total mask nonzeros
    if (sum(pw_sizes) != n_total) {
        stop("Internal error: sum(pathway_sizes) != nnz(mask). ",
             "This should not happen — please report a bug.")
    }

    ## ---- build null distribution --------------------------------------------
    set.seed(seed)
    null_dist <- matrix(NA_real_, nrow = n_perm, ncol = n_pathways)
    colnames(null_dist) <- names(observed)

    ## Precompute cumulative size boundaries for fast partitioning
    cum_sizes <- c(0L, cumsum(pw_sizes))

    if (verbose) cat("Running", n_perm, "permutations...\n")

    for (p in seq_len(n_perm)) {
        if (verbose && p %% 100 == 0) {
            cat(sprintf("  Permutation %d/%d\r", p, n_perm))
        }

        ## Shuffle the pooled weight values
        shuffled <- sample(abs_vals)

        ## Partition into pathway-sized bins and sum
        for (j in seq_len(n_pathways)) {
            start_idx <- cum_sizes[j] + 1L
            end_idx <- cum_sizes[j + 1L]
            null_dist[p, j] <- sum(shuffled[start_idx:end_idx])
        }
    }

    if (verbose) cat("\n")

    ## ---- compute statistics -------------------------------------------------
    null_means <- colMeans(null_dist)
    null_sds <- apply(null_dist, 2, sd)

    ## Protect against zero SD (happens if a pathway has size 1 or all
    ## weights are identical — unlikely but defensive)
    null_sds[null_sds == 0] <- .Machine$double.eps

    z_scores <- (observed - null_means) / null_sds

    ## Empirical p-values with pseudocount (Phipson & Smyth, 2010)
    p_values <- vapply(seq_len(n_pathways), function(j) {
        (sum(null_dist[, j] >= observed[j]) + 1L) / (n_perm + 1L)
    }, numeric(1))

    ## BH correction
    p_adj <- p.adjust(p_values, method = "BH")

    ## ---- assemble results ---------------------------------------------------
    result <- data.frame(
        pathway      = names(observed),
        observed     = unname(observed),
        pathway_size = pw_sizes,
        null_mean    = unname(null_means),
        null_sd      = unname(null_sds),
        z_score      = unname(z_scores),
        p_value      = unname(p_values),
        p_adj        = unname(p_adj),
        stringsAsFactors = FALSE
    )

    result <- result[order(result$p_value), ]
    rownames(result) <- NULL

    if (verbose) {
        n_sig <- sum(result$p_adj < 0.05)
        cat(sprintf("Significant pathways (BH < 0.05): %d / %d\n",
                    n_sig, n_pathways))
        cat(sprintf("Z-score range: %.2f to %.2f\n",
                    min(z_scores), max(z_scores)))
    }

    result
}


# =============================================================================
# Visualization of permutation results
# =============================================================================

#' Plot Permutation Significance Results
#'
#' Bar chart of observed pathway importance scores colored by statistical
#' significance from \code{\link{permutePathwayImportance}}.
#'
#' @param perm_result A \code{data.frame} returned by
#'   \code{permutePathwayImportance}.
#' @param alpha Numeric. Significance threshold for BH-adjusted p-values.
#'   Default 0.05.
#' @param top_n Integer. Number of top pathways to display. Default 20.
#' @param show_null Logical. Overlay null distribution mean +/- SD as
#'   error bars? Default TRUE.
#'
#' @return A \code{ggplot} object.
#' @export
plotPermutationResults <- function(perm_result,
                                   alpha = 0.05,
                                   top_n = 20L,
                                   show_null = TRUE) {

    stopifnot(is.data.frame(perm_result))
    required_cols <- c("pathway", "observed", "null_mean", "null_sd",
                       "p_adj", "z_score")
    missing_cols <- setdiff(required_cols, colnames(perm_result))
    if (length(missing_cols) > 0) {
        stop("perm_result is missing required columns: ",
             paste(missing_cols, collapse = ", "))
    }

    ## Subset to top_n (already sorted by p_value)
    plot_df <- utils::head(perm_result, top_n)

    ## Significance flag
    plot_df$significant <- ifelse(plot_df$p_adj < alpha, "Significant", "NS")

    ## Order pathways by observed importance
    plot_df$pathway <- factor(plot_df$pathway,
                              levels = rev(plot_df$pathway))

    ## Format p-value labels
    plot_df$p_label <- ifelse(
        plot_df$p_adj < 0.001, "***",
        ifelse(plot_df$p_adj < 0.01, "**",
               ifelse(plot_df$p_adj < 0.05, "*", ""))
    )

    p <- ggplot(plot_df, aes(x = .data$pathway, y = .data$observed,
                              fill = .data$significant)) +
        geom_col(width = 0.7) +
        coord_flip()

    ## Overlay null distribution reference
    if (show_null) {
        p <- p +
            geom_segment(
                aes(x = .data$pathway, xend = .data$pathway,
                    y = .data$null_mean - .data$null_sd,
                    yend = .data$null_mean + .data$null_sd),
                color = "gray40", linewidth = 0.8, alpha = 0.6
            ) +
            ggplot2::geom_point(
                aes(x = .data$pathway, y = .data$null_mean),
                color = "gray30", size = 1.5, shape = 18
            )
    }

    p <- p +
        ggplot2::scale_fill_manual(
            values = c("Significant" = "#b2182b", "NS" = "#92c5de"),
            name = paste0("BH p < ", alpha)
        ) +
        labs(
            title = "Pathway Importance: Observed vs. Permutation Null",
            subtitle = paste0("Top ", nrow(plot_df), " pathways | ",
                              "Gray diamonds = null mean +/- SD"),
            x = NULL,
            y = "Importance (sum |W * mask|)"
        ) +
        theme_minimal(base_size = 11) +
        theme(
            strip.text   = element_text(face = "bold"),
            axis.text.y  = element_text(size = 8),
            legend.position = "bottom"
        )

    p
}
